### ISSUE TITLE
Request for contributor onboarding?

### ISSUE THREAD

**Issue by CinchBlue** [ron-rs/ron#132]
Hi there,

What's the best way to get onboarded with development if we want to contribute?

Thanks.

**Comment by kvark** [comment]
@VermillionAzure you've already found our [gitter](https://gitter.im/ron-rs/ron), which is the right place to get all the onboarding info (instead of an issue).
Roughly, I think all you need is:
  1. be familiar with Rust
  2. be able to checkout the project and run the tests locally
  3. read the format specification to get a feel of it

Closing the issue with this. Let's continue on gitter ;)
