### ISSUE TITLE
[RFC] Add a tokenizer as intermediate step

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#178]
## Description

Add a tokenizer which emits `Token`s given a byte sequence.

Those tokens will then be feed into the deserializer.

## Motivation

This allows to simplify the logic in the deserializer, makes testing easier and is more likely to avoid bugs.

Additionally, we could refactor the `Serializer` to emit tokens, too (at a second step). If we do that, we might be able to address #175 by formatting the tokens; the pretty config would be mostly irrelevant for the serialization.

Aaand in a third step, we could even utilize this architecture to implement a formatter, simply by tokenizing an input file and pretty-formatting the tokens.

**Comment by cynecx** [comment]
Instead of implementing a new lexer, it's it possible to actually use rust's lexer? (https://crates.io/crates/).

**Comment by CAD97** [comment]
Specifically, rustc's lexer is now available as `rustc_lexer` at https://crates.io/crates/rustc_lexer and while it explicitly has no API guarantee other than adhering to semver, it is highly desired to have the crate compile on stable (with no intention of breaking that status). Since RON explicitly wants to "look like Rust", using the standard Rust lexer makes sense.

The other option is to use `proc_macro2` (and maybe `syn`?) to parse in all cases, which gives the `ron!` macro for free.

**Comment by CAD97** [comment]
I have _way_ too much experience writing syn-based parsers.

Here's a parser for the RON syntax using syn/proc_macro2: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ebed441bc90ad5bc0fef1bbe327e74f0

Feel free to use it. Also, double check me, I could've missed something.

**Comment by torkleyy** [comment]
I think we can leave this closed, it seems outside the scope of this repository and I've started something like this in ron-rs/ron-reboot
