### ISSUE TITLE
Design: trailing comma semantics

### ISSUE THREAD

**Issue by kvark** [ron-rs/ron#19]
Current proposal:
  - require trailing comma for maps and non-tuple structs (which have named fields)
  - optional comma for tuples and tuple structs

**Comment by Xaeroxe** [comment]
:+1: since I was CCed here on Gitter.  This proposal looks good to me.

**Comment by torkleyy** [comment]
It looked good to me at first, but I already hear people complaining about it.

**Comment by Xaeroxe** [comment]
@torkleyy We can't address a vague feeling of dissatisfaction.  What were the complaints?

**Comment by torkleyy** [comment]
There were no real complaints yet (since it's not implemented / used), but @vitvakatu found it weird and I think users would find it annoying if the parser fails because of a missing trailing comma (which isn't obvious). Furthermore, I think a trailing comma is useful, but should not be enforced just because of that fact; enforcing it would make it an anti-feature again. The simple and obvious solution would be to *allow* it everywhere, which would make the spec easier and it's also easier to keep in mind.

**Comment by Xaeroxe** [comment]
That sounds good to me, for our serializer can we have it insert trailing commas for structs though?

**Comment by torkleyy** [comment]
That's already the case.
