### ISSUE TITLE
How to specify whether to emit optional struct name during serialization?

### ISSUE THREAD

**Issue by Boscop** [ron-rs/ron#200]
How to specify whether to emit optional struct name during serialization?

I see no option for that here
https://docs.rs/ron/0.5.1/ron/ser/struct.PrettyConfig.html

but I think there should be one..

**Comment by kvark** [comment]
We've been discussing this in https://github.com/ron-rs/ron/issues/105#issuecomment-567256298 and the recent conclusion is that the bool must be moved into `PrettyConfig`.
Also, since we are at it, would be great to use the `#[non_exhaustive]` on the config, which just became available in stable rust.

If you want to take it, please do!
