### ISSUE TITLE
Feature: Type Declaration

### ISSUE THREAD

**Issue by ac566** [ron-rs/ron#242]
I'd love to see a macro/extension where we could provide an absolute or crate or working directory relative path to the types RON encodes. Would also be acceptable if crate paths are allowed as class/et al identifiers. Another idea would be adding scoped imports.

Example
```rust
/// As a scoped import
#![use("crate::my_mod::*")]
[
  /// As a macro/extension
  #![type("crate::my_mod::MyClass")]
  MyClass (
    a: 0,
    b: 100,
  ),
  /// As an identifier 
  crate::my_mod::MyClass (
    a: 0,
    b: 100,
  ),
  /// As a working directory path
  "./my_mod::MyClass" (
    a: 0,
    b: 100,
  ),
)
```

The motivation is to add the ability to statically analyze RON against a code-based schema and help support integrating with the language server.

Out of scope, but somewhat related would be some type of RON verification schema like [JSON](https://json-schema.org)

**Comment by kvark** [comment]
Thank you for filing!
This requests seems a bit strange to me. You want to be able to match RON against Rust sources without actually involving the Serde-based RON deserializer (that would otherwise tell you if the types match)? Like, if you could compile Rust code and link to that `crate::my_mod::MyClass` module, you would just do [ron::de::from_str::<MyClass>](https://docs.rs/ron/0.5.1/ron/de/fn.from_str.html).

**Comment by ac566** [comment]
I’m not sure I understand. I guess what I’m going for is that when writing Ron there’s no way to know it’s right until you try to deserialize it. But I want to know its right when typing it. It wouldn’t be needed in a packaged binary, but I figure it might be needed or rather useful for static analysis. Am I making sense, or am I over-complicating things?

**Comment by kvark** [comment]
If we are talking about IDE support and static analysis, I think I understand your point.
What I don't get is why this needs to be more granular than just a single line at the top of the RON file, e.g.  `#![type(std::Vec)]`.
Since the whole file is loaded as one type, and everything can be obtained by looking at it (i.e. parsing Rust code), there shouldn't be a need to specify it anywhere within RON (other than at start).

**Comment by torkleyy** [comment]
Maybe the way the RON IntelliJ plugin (which seems to be broken now) handled this can serve as some sort of inspiration.

I do agree with @kvark that a top level declaration should be sufficient.

**Comment by ac566** [comment]
My only issue with a single declaration being allowed it's not obvious how you would resolve ambiguous types, e.g. two structs with the same name? It's an edge case but I think it's a valid consideration.
