### ISSUE TITLE
No method named `depth_limit` found for struct `ron::ser::PrettyConfig` in the current scope

### ISSUE THREAD

**Issue by idoqo** [ron-rs/ron#296]
I'm working based on the encode example in the repo, and it seems the methods for configuring `PrettyConfig` were changed sometime before the current ron version (I'm using 0.6.4). Here's one of the errors I got from `cargo run`:
```
error[E0599]: no method named `depth_limit` found for struct `ron::ser::PrettyConfig` in the current scope
```
The fix was replacing:
```rust
let pretty = PrettyConfig::new()
        .depth_limit(2)
        .separate_tuple_members(true)
        .enumerate_arrays(true);
```
with:
```rust
let pretty = PrettyConfig::new()
        .with_depth_limit(2)
        .with_separate_tuple_members(true)
        .with_enumerate_arrays(true);
```

Maybe the code in the examples could be updated to reflect the changes?

**Comment by kvark** [comment]
Which example code do you mean, specifically? The actual `examples` are checked on CI, they always build against the code that lives here, independently of what's being published and what not.
Example code for v0.6 can be found in the relevant branch - https://github.com/ron-rs/ron/tree/v0.6

**Comment by idoqo** [comment]
This [`encode.rs`](https://github.com/ron-rs/ron/blob/master/examples/encode.rs) one, breaks around [#L42](https://github.com/ron-rs/ron/blob/3984332e191b9eb1f12b2a11fc7dd92cf56387e9/examples/encode.rs#L42) specifically. Don't know if it helps but here's the exact output of `cargo run`:
```

   Compiling ronn v0.1.0 (/tmp/ronn)
error[E0599]: no method named `depth_limit` found for struct `ron::ser::PrettyConfig` in the current scope
  --> src/main.rs:43:10
   |
43 |         .depth_limit(2)
   |          ^^^^^^^^^^^--- help: remove the arguments
   |          |
   |          field, not a method

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ronn`.

To learn more, run the command again with --verbose.
```

Also thanks for the link, I noticed the code in the (0.6) branch is correct. Maybe my mistake was using the examples from the master branch while importing v0.6.

**Comment by kvark** [comment]
> Maybe my mistake was using the examples from the master branch while importing v0.6.

Right. If you have ideas on how to make this clear, please shout out!
Going to close this, but please feel free to continue discussion.

**Comment by corjohnson** [comment]
Hello; I wanted to chime in on this just because I spent a little bit of time trying to figure out why I was having this issue as well. If the major release is considered the current version (say `0.6` at the time of writing this); could you update the default branch in the repo to match that? I think it would reduce confusion for new users and anyone wanting to reference the current examples. 

I know that's kind of a manual process.. so I totally understand if that isn't really an option.

**Comment by kvark** [comment]
@corjohnson where does this expectation comes from that GitHub default branch would correspond to the latest release?

**Comment by corjohnson** [comment]
The first thing people will see when they click on the repository link from crates.io is the master branch; and since the readme  presented in crates.io doesn't have any example code for encoding/decoding, the first place I would go is the examples, which on master are out of date with the released version on crates. 

That's where my expectation comes from at least

**Comment by kvark** [comment]
We could fix the link of the crate itself to point to the release branch, then

**Comment by corjohnson** [comment]
ah okay; that'd work awesome!
