### ISSUE TITLE
Map key uniqueness

### ISSUE THREAD

**Issue by SabrinaJewson** [ron-rs/ron#376]
As far as I can tell the Ron specification doesn't currently say anything about whether map keys are required to be unique or not. I think it would be good to either explicitly document that they aren't needed to be unique or explicitly document that they must be unique, so people can rely on that behaviour.

If I get the go-ahead one way or the other I would be happy to update the specification in the wiki about this.

**Comment by MomoLangenstein** [comment]
That's a good question. Since maps usually map to `HashMap`s or similar (like in `ron`'s `Value` type), this is a good place to look for the practicals. Given that we currently use `serde` for everything, https://github.com/serde-rs/serde/issues/1607 is relevant which describes that duplicate keys are simply overwritten instead of producing an error. You could of course also have some multimap type which deserialised from a map and makes proper use of duplicates. Right now it seems like `ron` in practice does allow duplicate keys. @torkleyy @kvark @SabrinaJewson Should we change this behaviour to be strict and disallow duplicates? If so, could we even catch duplicates?

**Comment by kvark** [comment]
The map is definitely not expecting duplicate keys. Whether this is detected by Serde or RON deserializer - looks like it's our job to detect this, based on (my brief reading of) the Serde bug mentioned?

**Comment by MomoLangenstein** [comment]
I think in the `serde` bug the solution was by having the user directly annotate the output datastructure with a wrapper that checks the result of `map.insert(key, val)`. To do this check in `ron`, I think we’d have to keep track of all keys already deserialised, which sounds horrible to me. I think the best thing we could do is say that `ron` expects unique keys but will not enforce it and link users to the proposed solution to check it themselves if they really do need uniqueness.

**Comment by kvark** [comment]
Yes, that sounds very reasonable to me!

**Comment by MomoLangenstein** [comment]
@SabrinaJewson Thanks for sparking this discussion with your question - would you like to update the documentation yourself?

**Comment by SabrinaJewson** [comment]
Can I just ask for clarification on what "expects" means - is it "it's recommended but not required by the spec", "It's implementation-defined" or "it's required but `ron-rs/ron` doesn't check every invariant of the spec"?

**Comment by MomoLangenstein** [comment]
Since the behaviour in case of duplicate keys is **implementation-defined** by the `Deserialize` implementation of the container, which we cannot control, I think the best we can do is recommend unique keys and state that what happens with duplicate keys depends on the (Rust) data structure which `ron` is deserialised into, and to link to https://docs.rs/serde_with/latest/serde_with/rust/maps_duplicate_key_is_error/index.html as a way to assert that keys are unique. So if one is just writing the RON document, then what happens with duplicate keys is undefined by `ron`.

**Comment by SabrinaJewson** [comment]
I've now documented this [in the specification](https://github.com/ron-rs/ron/wiki/Specification#maps) - thanks everyone!

**Comment by MomoLangenstein** [comment]
Thanks!
