### ISSUE TITLE
`indexmap` feature has transitive dependency on `hashbrown` v0.12.1 with MSRV 1.56.0

### ISSUE THREAD

**Issue by MomoLangenstein** [ron-rs/ron#383]
https://github.com/ron-rs/ron/runs/6951586367

**Comment by MomoLangenstein** [comment]
It seems we can either enforce `1.0.2 >= indexmap < 1.9` or upgrade our MSRV to 1.56.0, as `hashbrown` and `indexmap` have both done in the last few days.

**Comment by torkleyy** [comment]
For 0.7 we use locked versions of indexmap and bitflags anyway, so that shouldn't be a problem.
I'm hesitant about bumping the msrv to 1.56 because that might slow down adoption of a new ron release which in turn might delay a release from master. I'm hoping we can release 0.8 soon-ish, because 0.7 has already diverged enough and there are some valuable changes (like your error refactoring) that need a minor bump.

**Comment by MomoLangenstein** [comment]
> For 0.7 we use locked versions of indexmap and bitflags anyway

Where do we lock the version? I don't see a difference with the main branch for this

**Comment by torkleyy** [comment]
I think what I really wanted to say is that these projects already have to lock those versions to compile successfully. But we do lock the version here:

https://github.com/ron-rs/ron/blob/1ae8b8c3a0f28be8f2a8851bda1e6baa8cb6bc39/.github/workflows/ci.yaml#L37

**Comment by MomoLangenstein** [comment]
Oh, I see! The MSRV on 0.7 is still 1.36 anyways.

How will we handle such breakage in the future?
