### ISSUE TITLE
[RFC] Separate number types

### ISSUE THREAD

**Issue by kvark** [ron-rs/ron#47]
See https://www.reddit.com/r/rust/comments/6sm6i2/rusty_object_notation/dlei3gp/

Basically, Rust clearly differentiates between integer types and floating points - there is no ambiguity. No reason for Ron to mix those types either.

**Comment by Aceeri** [comment]
How about adding in typed numbers like in rust: `32u32`, `5.0f64`, etc. ?

**Comment by kvark** [comment]
@Aceeri I think it would be an overkill. Loading everything as u64 and f64 should be good enough. After all, we are talking about a text format here, not the crazily optimized binary representation.

**Comment by mrZalli** [comment]
What if you loaded integers as BigInts from [num](https://docs.rs/num/0.1.40/num/) crate since they can handle arbitrarily large numbers and then convert to the target integer or other type that can be converted from it. This would be great if [128-bit support](https://github.com/rust-lang/rust/issues/35118) ever comes to stable, or we want to use it in nightly, and we want to represent 128-bit number literals in ron text, instead of bypassing the 64-bit limitation with something like using a two 64-bit integer tuple or a quoted string representation, or you know if we wanted to store BigInts.

**Comment by kvark** [comment]
@mrZalli hmm, wouldn't it be up to `BigInt` implementation to figure out how it's going to be serialized/deserialized?
128 bit would be nice but not essential, strictly speaking. Numbers as big are not readable anyway, so you might as well pass them as a hex string.

**Comment by torkleyy** [comment]
Related: https://github.com/ron-rs/ron/issues/100

**Comment by kvark** [comment]
@torkleyy 
> I don't think we need to be super concise here, so 5 as float is fine for me.

Do you find it better than just "5.0"? And if so, why?

**Comment by torkleyy** [comment]
Not better, but also acceptable.

**Comment by cart** [comment]
I have a use case that makes the `5` vs `5.0` distinction important. My rust type is a dynamic collection that can contain either floats or ints. Round tripping a value of `5.0` with ron results in an integer output of `5` when its source was a float.

In the short term I have forked ron to support this use case, but I'd love to get this upstreamed if possible:
https://github.com/ron-rs/ron/pull/237

**Comment by SirWindfield** [comment]
Again, not sure about `serde` internals here but given the following struct:
```rust
#[derive(Deserialize)]
struct Config {
	float: f32,
    integer: u8,
}
```
and this config:
```ron
Config(
    float: 5.0,
    integer: 255
)
```

Would `ron` just use `f64/u64` in this case internally and `serde` would allow to map those to the concrete types (and conditionally throw an error if the conversion fails due to overflow)?

Apart from that, I've read the reddit comment and am on the same page /u/LEmp_Evrey:
- `f64` for floating point numbers based on opt-in, e.g. you have to append a fractional part.
- `u64` for integers that do explicitly state that they are unsigned, e.g. `+4`.
- `i64` for numbers without any explicit marker traits.

Thoughts?
