### ISSUE TITLE
Non-intuitive interaction with #[enable(implicit_some)]

### ISSUE THREAD

**Issue by NiloDrumond** [ron-rs/ron#540]
I'm not sure if this is some kind of bug, incomplete/non-intuitive documentation or just me being incompetent at reading the docs, but I decided to share it anyway.

I have this simple struct:
```rust
#[derive(Serialize, Deserialize, Default, Debug)]
struct ScraperState {
    pub repos_query_at: Option<DateTime<Utc>>,
}
```

Which I write to a .ron file like this:

```rust
fn save_state(state: ScraperState) -> Result<(), Box<dyn Error>> {
    let mut file = File::create(STATE_PATH)?;
    let ron_string = ron::ser::to_string_pretty(&state, ron::ser::PrettyConfig::default())?;
    file.write_all(ron_string.as_bytes())?;
    Ok(())
}
```

If I pass a state with `repos_query_at: None`, the output .ron file will be:
```
(
    repos_query_at: None,
)
```

I then tried to load it like this:
```rust
fn load_state() -> Option<ScraperState> {
    let mut state_file = match File::open(STATE_PATH) {
        Ok(file) => file,
        Err(_) => return None,
    };
    let mut buf: String = String::new();
    if let Err(e) = state_file.read_to_string(&mut buf) {
        println!("Error reading file: {:?}", e);
        return None;
    }
    let state: Option<ScraperState> = match ron::from_str(&buf) {
        Ok(state) => state,
        Err(e) => {
            println!("Error deserializing RON: {:?}", e);
            None
        },
    };
    state
}
```
But I was getting the error: `Error deserializing RON: SpannedError { code: ExpectedOption, position: Position { line: 1, col: 1 } }`.

I was confused for a while, not really understanding what I did wrong, considering how simple my implementation was. Eventually, I stumbled across `#[enable(implicit_some)]`, which if I add on top of the .ron file solves the problem. Now by simply adding the line `let ron_string = "#![enable(implicit_some)]\n".to_owned() + &ron_string;` to my save_state function, everything works fine. 

What I consider weird is that I didn't opt-in for any "non-standard" rules for my .ron output when I was serializing the struct. I thought that maybe the `PrettyConfig::default()` had something to do with it, but using `to_string()` instead of `to_pretty_string()` yielded the same result.

The default way of serializing outputting a .ron file that can't be de-serialized by the default way of de-serializing seems non-intuitive to me. If this is not a bug, then maybe improving the `ExpectedOption` Error to point to this `implicit_some` extension might be a good idea?

**Comment by juntyr** [comment]
Hi, thank you for the question!

Your bug is in these two lines:
```rust
let state: Option<ScraperState> = match ron::from_str(&buf) {
    Ok(state) => state,
```
where you are asking RON to deserialise your string buffer `buf` into the type `Option<ScraperState>`. What RON now expects is one of two things:

* either the string `None`
* or something like `Some((repos_query_at: ..))` where `..` just abbreviates the serialised `Option<DateTime<Utc>>` value, in your case `Some((repos_query_at: None))`

However, the string you pass it is `(repos_query_at: None)`, i.e. you're asking RON for a `Option<ScraperState>` but giving it a `ScraperState`.

What you probably meant to write is:
```rust
let state: Option<ScraperState> = match ron::from_str(&buf) {
    Ok(state) => Some(state), // note the Some here
```
which should fix your bug.

Now why were you able to use the `#[enable(implicit_some)]` feature to "fix" your problem? This feature allows you to omit a `Some` and to just write the inner part, which allowed RON to transform a `ScraperState` into an `Option<ScraperState>`.

What documentation should we add that would have made it easier for you to know where the bug was yourself?

I hope this helps :)

**Comment by NiloDrumond** [comment]
@juntyr 

I think it makes sense now. Just to be sure, the reason my first implementation wasn't working was because I was serializing `ScraperState` but trying to de-serialize it to `Option<ScraperState>` right?

That's why this works too?
```rust
    let state: ScraperState = match ron::from_str(&buf) {
        Ok(state) => state,
        Err(e) => {
            println!("Error deserializing RON: {:?}", e);
            return None;
        },
    };
```

If that's indeed the case, then I guess it was just my lack of knowledge of serde and Rust in general. There really isn't much ron can do if I'm using different types to serialize and de-serialize, so I'm happy to close this issue as is.

In terms of possibly improving the documentation, if my question is an isolated case, I don't think it's needed. But if I'm not the first or last to ask this question, or similar questions are commonly asked, then maybe a FAQ section for the wiki could be a good idea?
