### ISSUE TITLE
Please use `Cow<'static, str>` for configuration, rather than `String`.

### ISSUE THREAD

**Issue by maypop-the-dragon** [ron-rs/ron#545]
**Please use `Cow<'static, str>` for configuration, rather than `String`.**

This way, we will not have to allocate new `String`s all the time even when the strings are always the same.
This will also make it possible to construct configurations in `const` contexts.

This will allow for cleaner code and slightly improved performance.

**How it is now:**

```rs
// This is a config that we will use repeatedly throughout the program.
// It must be inside the body of a function because allocating `String`s is not `const`.
let config = PrettyConfig::new()
    .indentor("\t".to_string())
    .struct_names(true);

// These all involve allocating new `String`s for the new line, indentor, and separator.
println!("{}", to_string_pretty(struct_1, config.clone()).unwrap());
println!("{}", to_string_pretty(struct_2, config.clone()).unwrap());
println!("{}", to_string_pretty(struct_3, config.clone()).unwrap());
```

**How I imagine it could be:**

```rs
// This can now be global if we want!
const CONFIG: PrettyConfig = PrettyConfig::new()
    .indentor(Cow::Borrowed("\t"))
    .struct_names(true);

// This is now cheaper and cleaner.
println!("{}", to_string_pretty(struct_1, CONFIG).unwrap());
println!("{}", to_string_pretty(struct_2, CONFIG).unwrap());
println!("{}", to_string_pretty(struct_3, CONFIG).unwrap());
```

*P.S. This is my first GitHub issue so sorry if it's, like, bad somehow.*

**Comment by juntyr** [comment]
Thank you for your very well-written issue, @maypop-the-dragon!

I agree that using Cow<str> instead of String would be more ergonomic, especially if the confit setter methods would take Into<Cow<str>> as a parameter.

The lifetime of the Cow is of course an important question. With ‘static we’d allow the optimisation only for const config values, which should cover most cases. Dynamic values would still need to allocate, but by keeping the Cow const we’d not have to add any new lifetime bounds.

Overall, I like this idea! Do you want to open a PR yourself with this change? I’m very swamped myself atm.

**Comment by maypop-the-dragon** [comment]
@juntyr, this is my first time doing this, so I might need help.
Could you at least link me to a good tutorial, and are there any guidelines I should follow?

**Comment by maypop-the-dragon** [comment]
Oops! Sorry, I clicked the wrong button! Again, first time.

**Comment by Coca162** [comment]
Just as a note but if this is done and `PrettyConfig::new` is made `const` this would still not allow users of the library to change the `Cow` fields in a constant context due to the compiler assuming `Cow` drops are not `const` (https://github.com/rust-lang/rust/issues/73255), and the only way to construct `PrettyConfig`s is via updating (and thusly dropping) the default (due to `#[non_exhaustive]`).
